### ISSUE TITLE
Zhongwen 4.14.0 causes missed keypresses in some text fields on Firefox 59.0.2 (64-bit)

### ISSUE THREAD

**Issue by haelduksf** [leezu/zhongwen#10]
Using Zhongwen 4.14.0 with Firefox 59.0.2 (64-bit), keypresses are missed in some cases. The most consistent way I've found to reproduce this is:

Open GMail
Hit "reply" on any email
Enter text in the reply box
Highlight text in the reply box
Attempt to enter new text (with text highlighted). 

Most keys work, but some keys don't. The ones that don't work (so far I've found tyasgxbn) all appear to be associated with Zhongwen shortcuts. Disabling Zhongwen fixes the issue. 

Let me know if you want more info or if I can lend a hand with the fix.

**Comment by leezu** [comment]
Thanks haelduksf. With disabling Zhongwen, do you mean disabling the extension in the about:addons page of the browser or toggling if Zhongwen is actively trying to look up words for you, by pressing the Zhongwen icon in the upper right corner of your browsers window?

**Comment by haelduksf** [comment]
I mean toggling if Zhongwen is active.

**Comment by leezu** [comment]
I couldn't reproduce the behaviour yet. What OS are you on?

**Comment by leezu** [comment]
Though I'm on Firefox 58, waiting for https://bugs.gentoo.org/650472 . Did you only start experiencing this issue with FF 59?

**Comment by haelduksf** [comment]
I'm on Windows 10. I'm not sure which build I was on when I first started
seeing the issue, but I'm pretty sure it was before FF 59.

**Comment by leezu** [comment]
Are you comfortable with code?
While I can't reproduce this on Linux and OS X, the following change might be related: https://github.com/leezu/zhongwen/commit/06f2cb17e1ed4760806dab6b1c211c8017d968da

You could check out the current version of the repository, delete the changed line in `content.js` and open a new browser session with the adapted addon code by running [`web-ext run`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext). Please let me know if that helps.

**Comment by leezu** [comment]
I could reproduce the bug now.

Initially I used the "new message" function in gmail, which is different to the "reply function" that you mentioned. (I'm not a gmail user so I didn't have any message there to reply to). I will see if I can fix the bug soon/find the root cause.

**Comment by haelduksf** [comment]
Sorry for the late response- I was travelling for work. The change is
working for me. Thanks!

-A
