### ISSUE TITLE
*ǚ missing zhuyin

### ISSUE THREAD

**Issue by imd** [leezu/zhongwen#20]
If you hover over 女 or 呂 with zhuyin enabled, it says "undefined ˇ".

It should say "ㄋㄩˇ" or "ㄌㄩˇ" respectively.

**Comment by CNurt** [comment]
I just had a look and it seems all the syllables with 'ü' in 'content.js' have two problems.
1. pinyin on the left side does not match the pinyin used to query the list 'zhuyinMap'
2. corresponding zhuyin on right side is not correct

fix 1.: replacing the '' character with 'u:' works correctly for me
fix 2.: just copy the correct unicode string

some more characters for testing:
`女 nǚ ㄋㄩˇ`
`吕 lǚ ㄌㄩˇ`
`虐 nüè ㄋㄩㄝˋ`
`略 lüè ㄌㄩㄝˋ`

I just opened a pull request and wait for it to close, afterwards I can fix this one.
