### ISSUE TITLE
Attempting to load extension results in chrome incompatibility errors

### ISSUE THREAD

**Issue by alexandresmirnov** [leezu/zhongwen#24]
Forking the repo and attempting to load it as an unpacked extension in chrome (68) does not allow the extension to run properly, due to using global variables that not defined in chrome.

The background extension points to line 8 of background.js as the (first) problem: `browser.runtime.onMessage...`.  The issue is that `browser` is undefined in chrome, and it looks like what should be used is the `chrome` global instead.  Inspecting the code of the working extension on the chrome store, the corresponding line is `chrome.extension.onRequest...`.

What is causing the discrepancy between the code in the repo and what works on chrome?  Is there some sort of pre-compile step necessary before loading the extension into chrome?  I would love any clarification on this!

**Comment by leezu** [comment]
Hi @alexandresmirnov, @cschiller has refactored the code and there is now a shared codebase for the Firefox and Chrome version in the master branch.
