### ISSUE TITLE
Popup not staying enabled between sessions 

### ISSUE THREAD

**Issue by nickbclifford** [leezu/zhongwen#7]
I'm using Firefox Developer Edition 58.0b5, and I just noticed that when I start a new Firefox session, the popups are disabled, even though I'm toggling them on in the last session. A cursory search in the preferences did not reveal anything. I'm assuming this is a bug since the Chrome extension does not have this issue.

**Comment by leezu** [comment]
This should be fixed in the newest version. Can you confirm that?

**Comment by nickbclifford** [comment]
Yep, fixed. Thanks!
