### ISSUE TITLE
Can't disable wordlist context menu entry 

### ISSUE THREAD

**Issue by Thomasc5** [leezu/zhongwen#8]
Could you add an option to disable the "Open word list" context menu entry?

**Comment by leezu** [comment]
That's feasible, but what would be a reason to disable it?

**Comment by Thomasc5** [comment]
@leezu I work in a library and I have to do a few hundred right-click searches daily. I used to use an add-on called "Menu Wizard" to re-arrange and to control the sprawling of the context menu entries, but now with the add-on deprecated in the new Firefox, it's a daily struggle.

**Comment by leezu** [comment]
@Thomasc5 Doesn't the context menu only show up if you right click the addon icon in the "menu bar"? Is it disturbing you there? Or where does the menu entry show up causing you issues? Can you send a screenshot?

**Comment by Thomasc5** [comment]
@leezu I am not with my work computer now but I have just figured out that I can re-install the older version (4.9.5a), so when the popup dictionary is not active, the wordlist context menu entry will not appear on in the context menu.

**Comment by leezu** [comment]
@Thomasc5 yes, I have changed the behaviour in the latest version. I still don't get in what context the menu entry is disturbing you (i.e. where it is showing up) and will be happy to fix it then.

**Comment by Thomasc5** [comment]
@leezu It's a bit like a setting up an IDE;  our right-click context menus are all carefully "manicured" --  most often used entries will be arranged near to the top & middle, less often used ones will be nested, seldom/never used entries will be hidden.  

But with the new Firefox 57, the whole context menu is unconfigurable. That's why I hope a checkbox could be added to disable the "Open word list" in context menu. 

Thank you.

**Comment by leezu** [comment]
It is fixed in the most recent version. Please re-open in case you have further issues.
For clarification, we were talking about different context menus before. You meant the "page" context menu entry whereas I thought about the "browser_action" context menu entry ( https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus/ContextType )..
